import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Download, FileUp, Plus, Save, UserRound, X } from "lucide-react";
import { StatusBadge } from "../components/common/StatusBadge";
import { demoPlan } from "../lib/data";
import { importSimBriefFlight, listFlightPlans, saveFlightPlan } from "../lib/tauri";
import type { FlightPlan } from "../types";

const localKey = "skyboard-efb-flight-plans";
function sortByImportTime(plans: FlightPlan[]) { return [...plans].sort((first, second) => Date.parse(second.importedAt || second.updatedAt) - Date.parse(first.importedAt || first.updatedAt)); }
function browserPlans() { try { const raw = localStorage.getItem(localKey); const plans = raw ? JSON.parse(raw) as FlightPlan[] : [demoPlan]; return sortByImportTime(plans.map((plan) => ({ ...plan, importedAt: plan.importedAt || plan.updatedAt || new Date(0).toISOString(), routePoints: plan.routePoints ?? [] }))); } catch { return [demoPlan]; } }
function cachePlans(plans: FlightPlan[]) { localStorage.setItem(localKey, JSON.stringify(sortByImportTime(plans))); }
function localDateTime(value: string) { const timestamp = Date.parse(value); return Number.isNaN(timestamp) ? new Date().toISOString().slice(0, 16) : new Date(timestamp).toISOString().slice(0, 16); }
function downloadPlan(plan: FlightPlan) { const url = URL.createObjectURL(new Blob([JSON.stringify(plan, null, 2)], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${plan.callsign || plan.departure}-${plan.arrival}.json`; anchor.click(); URL.revokeObjectURL(url); }

export function FlightPlansPage() {
  const client = useQueryClient();
  const plansQuery = useQuery({ queryKey: ["flight-plans"], queryFn: async () => { const plans = await listFlightPlans(); return plans.length ? plans : browserPlans(); } });
  const [editing, setEditing] = useState<FlightPlan | null>(null);
  const [simbriefOpen, setSimbriefOpen] = useState(false);
  const [username, setUsername] = useState("");
  const plans = useMemo(() => plansQuery.data ?? [], [plansQuery.data]);
  useEffect(() => { if (!plansQuery.isLoading && plans.length === 0) setEditing(demoPlan); }, [plansQuery.isLoading, plans.length]);
  const mutation = useMutation({ mutationFn: async (plan: FlightPlan) => { const result = await saveFlightPlan(plan); cachePlans([result, ...plans.filter((item) => item.id !== result.id)]); return result; }, onSuccess: () => { client.invalidateQueries({ queryKey: ["flight-plans"] }); setEditing(null); } });
  const simbriefMutation = useMutation({ mutationFn: async (username: string) => { const flight = await importSimBriefFlight(username); const importedAt = new Date().toISOString(); return saveFlightPlan({ id: crypto.randomUUID(), callsign: flight.callsign, departure: flight.departure, arrival: flight.arrival, alternate: flight.alternate, route: flight.route, aircraft: flight.aircraft, cruiseAltitude: flight.cruiseAltitude, etd: localDateTime(flight.scheduledOut), status: "草稿", updatedAt: importedAt, importedAt, routePoints: flight.routePoints }); }, onSuccess: (plan) => { cachePlans([plan, ...plans.filter((item) => item.id !== plan.id)]); client.invalidateQueries({ queryKey: ["flight-plans"] }); setEditing(plan); setSimbriefOpen(false); setUsername(""); } });
  const newPlan = (): FlightPlan => { const importedAt = new Date().toISOString(); return { ...demoPlan, id: crypto.randomUUID(), callsign: "", departure: "ZBAA", arrival: "ZSPD", route: "", etd: new Date().toISOString().slice(0, 16), status: "草稿", updatedAt: importedAt, importedAt, routePoints: [] }; };
  return <div className="flight-page page-stack"><div className="page-actions"><div><h2>飞行计划</h2><p>本地保存，支持导入 SimBrief 最近一次 OFP。</p></div><div><button className="button secondary" onClick={() => { setSimbriefOpen(true); simbriefMutation.reset(); }}><FileUp size={17} />导入 SimBrief</button><button className="button primary" onClick={() => setEditing(newPlan())}><Plus size={17} />新建计划</button></div></div>
    <section className="panel plan-table"><div className="plan-table-head"><span>呼号 / 机型</span><span>航线</span><span>计划起飞</span><span>状态</span><span /></div>{plans.map((plan) => <button className="plan-row" onClick={() => setEditing(plan)} key={plan.id}><span><strong>{plan.callsign || "未命名计划"}</strong><small>{plan.aircraft}</small></span><span><strong>{plan.departure} <i>→</i> {plan.arrival}</strong><small>{plan.route || "未设置航路"}</small></span><span>{new Date(plan.etd).toLocaleString("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" })}</span><span><StatusBadge tone={plan.status === "计划中" ? "info" : "neutral"}>{plan.status}</StatusBadge></span><span>编辑</span></button>)}</section>
    {simbriefOpen && <div className="modal-backdrop" role="presentation"><section className="modal-panel simbrief-modal" role="dialog" aria-modal="true" aria-label="导入 SimBrief 飞行计划"><div className="modal-header"><div><p className="eyebrow">SIMBRIEF IMPORT</p><h2>导入最近飞行计划</h2></div><button className="icon-button" onClick={() => setSimbriefOpen(false)}><X size={20} /></button></div><p className="simbrief-description">输入 SimBrief 用户名。应用会通过官方 API 读取该用户最近一次生成的飞行计划，并填充到可编辑草稿。</p><label className="form-field"><span>SimBrief 用户名</span><div className="input-with-icon"><UserRound size={17} /><input autoFocus value={username} onChange={(event) => setUsername(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && username.trim()) simbriefMutation.mutate(username); }} placeholder="例如 your_simbrief_username" /></div></label>{simbriefMutation.isError && <p className="form-error">{simbriefMutation.error.message}</p>}<div className="modal-actions"><button className="button secondary" onClick={() => setSimbriefOpen(false)}>取消</button><button className="button primary" disabled={!username.trim() || simbriefMutation.isPending} onClick={() => simbriefMutation.mutate(username)}><FileUp size={17} />{simbriefMutation.isPending ? "正在导入" : "读取最近 OFP"}</button></div></section></div>}
    {editing && <div className="modal-backdrop" role="presentation"><section className="modal-panel" role="dialog" aria-modal="true" aria-label="编辑飞行计划"><div className="modal-header"><div><p className="eyebrow">FLIGHT PLAN</p><h2>{editing.id === demoPlan.id ? "编辑飞行计划" : "新建飞行计划"}</h2></div><button className="icon-button" onClick={() => setEditing(null)}><X size={20} /></button></div><form onSubmit={(event) => { event.preventDefault(); mutation.mutate({ ...editing, updatedAt: new Date().toISOString() }); }}><div className="form-grid"><Field label="呼号" value={editing.callsign} onChange={(callsign) => setEditing({ ...editing, callsign })} placeholder="例如 CSN 6981" /><Field label="机型" value={editing.aircraft} onChange={(aircraft) => setEditing({ ...editing, aircraft })} /><Field label="出发机场" value={editing.departure} onChange={(departure) => setEditing({ ...editing, departure: departure.toUpperCase() })} /><Field label="到达机场" value={editing.arrival} onChange={(arrival) => setEditing({ ...editing, arrival: arrival.toUpperCase() })} /><Field label="备降机场" value={editing.alternate ?? ""} onChange={(alternate) => setEditing({ ...editing, alternate: alternate.toUpperCase() })} /><Field label="巡航高度" value={editing.cruiseAltitude} onChange={(cruiseAltitude) => setEditing({ ...editing, cruiseAltitude })} /><label className="form-field full"><span>航路</span><textarea value={editing.route} onChange={(event) => setEditing({ ...editing, route: event.target.value })} placeholder="输入航路点与航路" /></label><label className="form-field"><span>预计起飞时间</span><input type="datetime-local" value={editing.etd} onChange={(event) => setEditing({ ...editing, etd: event.target.value })} /></label><label className="form-field"><span>状态</span><select value={editing.status} onChange={(event) => setEditing({ ...editing, status: event.target.value as FlightPlan["status"] })}><option>草稿</option><option>计划中</option><option>已完成</option></select></label></div><div className="modal-actions"><button type="button" className="button secondary" onClick={() => downloadPlan(editing)}><Download size={17} />导出计划</button><button type="button" className="button secondary" onClick={() => setEditing(null)}>取消</button><button className="button primary" disabled={mutation.isPending}><Save size={17} />{mutation.isPending ? "正在保存" : "保存到本机"}</button></div>{mutation.isError && <p className="form-error">保存失败：{mutation.error.message}</p>}</form></section></div>}
  </div>;
}
function Field({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string }) { return <label className="form-field"><span>{label}</span><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></label>; }
