import { useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CalendarClock, Download, FileText, FileUp, Gauge, Plane, PlaneLanding, PlaneTakeoff, Plus, Route, Save, UserRound, X } from "lucide-react";
import { demoPlan } from "../lib/data";
import { importSimBriefFlight, listFlightPlans, saveFlightPlan } from "../lib/tauri";
import type { FlightPlan } from "../types";

const localKey = "skyboard-efb-flight-plans";
const simbriefUsernameKey = "skyboard-efb-simbrief-username";
function sortByImportTime(plans: FlightPlan[]) { return [...plans].sort((first, second) => Date.parse(second.importedAt || second.updatedAt) - Date.parse(first.importedAt || first.updatedAt)); }
function browserPlans() { try { const raw = localStorage.getItem(localKey); const plans: Array<FlightPlan & { status?: unknown }> = raw ? JSON.parse(raw) as Array<FlightPlan & { status?: unknown }> : [demoPlan]; return sortByImportTime(plans.map(({ status: _status, ...plan }) => ({ ...plan, importedAt: plan.importedAt || plan.updatedAt || new Date(0).toISOString(), routePoints: plan.routePoints ?? [] }))); } catch { return [demoPlan]; } }
function cachePlans(plans: FlightPlan[]) { localStorage.setItem(localKey, JSON.stringify(sortByImportTime(plans))); }
function savedSimbriefUsername() { try { return localStorage.getItem(simbriefUsernameKey) ?? ""; } catch { return ""; } }
function cacheSimbriefUsername(username: string) { try { localStorage.setItem(simbriefUsernameKey, username); } catch { return; } }
function localDateTime(value: string) { const timestamp = Date.parse(value); return Number.isNaN(timestamp) ? new Date().toISOString().slice(0, 16) : new Date(timestamp).toISOString().slice(0, 16); }
function downloadPlan(plan: FlightPlan) { const url = URL.createObjectURL(new Blob([JSON.stringify(plan, null, 2)], { type: "application/json" })); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${plan.callsign || plan.departure}-${plan.arrival}.json`; anchor.click(); URL.revokeObjectURL(url); }

export function FlightPlansPage() {
  const client = useQueryClient();
  const plansQuery = useQuery({ queryKey: ["flight-plans"], queryFn: async () => { const plans = await listFlightPlans(); return plans.length ? plans : browserPlans(); } });
  const [editing, setEditing] = useState<FlightPlan | null>(null);
  const [editingMode, setEditingMode] = useState<"new" | "edit">("edit");
  const [simbriefOpen, setSimbriefOpen] = useState(false);
  const [username, setUsername] = useState(savedSimbriefUsername);
  const [activationMessage, setActivationMessage] = useState("");
  const plans = useMemo(() => plansQuery.data ?? [], [plansQuery.data]);
  useEffect(() => { if (!plansQuery.isLoading && plans.length === 0) { setEditingMode("edit"); setEditing(demoPlan); } }, [plansQuery.isLoading, plans.length]);
  const mutation = useMutation({ mutationFn: async (plan: FlightPlan) => { const result = await saveFlightPlan(plan); cachePlans([result, ...plans.filter((item) => item.id !== result.id)]); return result; }, onSuccess: () => { client.invalidateQueries({ queryKey: ["flight-plans"] }); setEditing(null); } });
  const simbriefMutation = useMutation({ mutationFn: async (username: string) => { const flight = await importSimBriefFlight(username.trim()); const importedAt = new Date().toISOString(); return saveFlightPlan({ id: crypto.randomUUID(), callsign: flight.callsign, departure: flight.departure, arrival: flight.arrival, alternate: flight.alternate, route: flight.route, aircraft: flight.aircraft, cruiseAltitude: flight.cruiseAltitude, etd: localDateTime(flight.scheduledOut), updatedAt: importedAt, importedAt, routePoints: flight.routePoints }); }, onSuccess: (plan, importedUsername) => { const cachedUsername = importedUsername.trim(); cacheSimbriefUsername(cachedUsername); setUsername(cachedUsername); cachePlans([plan, ...plans.filter((item) => item.id !== plan.id)]); client.invalidateQueries({ queryKey: ["flight-plans"] }); setEditingMode("edit"); setEditing(plan); setSimbriefOpen(false); } });
  const activateMutation = useMutation({ mutationFn: async (plan: FlightPlan) => { const importedAt = new Date().toISOString(); return saveFlightPlan({ ...plan, updatedAt: importedAt, importedAt }); }, onSuccess: (plan) => { const updatedPlans = [plan, ...plans.filter((item) => item.id !== plan.id)]; cachePlans(updatedPlans); client.setQueryData(["flight-plans"], updatedPlans); client.invalidateQueries({ queryKey: ["flight-plans"] }); setActivationMessage(`已导入 ${plan.callsign || `${plan.departure}-${plan.arrival}`}，地图航路已切换。`); } });
  const activatePlan = (plan: FlightPlan) => { if (window.confirm(`确认将 ${plan.callsign || "此计划"}（${plan.departure} → ${plan.arrival}）导入为当前飞行计划？`)) activateMutation.mutate(plan); };
  const newPlan = (): FlightPlan => { const importedAt = new Date().toISOString(); return { ...demoPlan, id: crypto.randomUUID(), callsign: "", departure: "ZBAA", arrival: "ZSPD", route: "", etd: new Date().toISOString().slice(0, 16), updatedAt: importedAt, importedAt, routePoints: [] }; };
  return <div className="flight-page page-stack"><div className="page-actions"><div><h2>飞行计划</h2><p>点击历史计划并确认后可直接切换为当前地图航路。</p></div><div><button className="button secondary" onClick={() => { setSimbriefOpen(true); simbriefMutation.reset(); }}><FileUp size={17} />导入 SimBrief</button><button className="button primary" onClick={() => { setEditingMode("new"); setEditing(newPlan()); }}><Plus size={17} />新建计划</button></div></div>
    {activationMessage && <p className="success-message">{activationMessage}</p>}
    <section className="panel plan-table"><div className="plan-table-head"><span>呼号 / 机型</span><span>航线</span><span>计划起飞</span><span>操作</span></div>{plans.map((plan) => <div className="plan-row" role="button" tabIndex={0} onClick={() => activatePlan(plan)} onKeyDown={(event) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); activatePlan(plan); } }} key={plan.id}><span><strong>{plan.callsign || "未命名计划"}</strong><small>{plan.aircraft}</small></span><span><strong>{plan.departure} <i>→</i> {plan.arrival}</strong><small>{plan.route || "未设置航路"}</small></span><span>{new Date(plan.etd).toLocaleString("zh-CN", { month: "2-digit", day: "2-digit", hour: "2-digit", minute: "2-digit" })}</span><button className="plan-row-edit" onClick={(event) => { event.stopPropagation(); setEditingMode("edit"); setEditing(plan); }}>编辑</button></div>)}</section>
    {simbriefOpen && <div className="modal-backdrop" role="presentation"><section className="modal-panel simbrief-modal" role="dialog" aria-modal="true" aria-label="导入 SimBrief 飞行计划"><div className="modal-header"><div><p className="eyebrow">SIMBRIEF IMPORT</p><h2>导入最近飞行计划</h2></div><button className="icon-button" onClick={() => setSimbriefOpen(false)}><X size={20} /></button></div><p className="simbrief-description">输入 SimBrief 用户名。应用会通过官方 API 读取该用户最近一次生成的飞行计划，并填充到可编辑草稿。</p><label className="form-field"><span>SimBrief 用户名</span><div className="input-with-icon"><UserRound size={17} /><input autoFocus value={username} onChange={(event) => { setUsername(event.target.value); cacheSimbriefUsername(event.target.value); }} onKeyDown={(event) => { if (event.key === "Enter" && username.trim()) simbriefMutation.mutate(username); }} placeholder="例如 your_simbrief_username" /></div></label>{simbriefMutation.isError && <p className="form-error">{simbriefMutation.error.message}</p>}<div className="modal-actions"><button className="button secondary" onClick={() => setSimbriefOpen(false)}>取消</button><button className="button primary" disabled={!username.trim() || simbriefMutation.isPending} onClick={() => simbriefMutation.mutate(username)}><FileUp size={17} />{simbriefMutation.isPending ? "正在导入" : "读取最近 OFP"}</button></div></section></div>}
    {editing && <FlightPlanEditor plan={editing} mode={editingMode} pending={mutation.isPending} error={mutation.isError ? mutation.error.message : ""} onChange={setEditing} onClose={() => setEditing(null)} onExport={() => downloadPlan(editing)} onSubmit={() => mutation.mutate({ ...editing, updatedAt: new Date().toISOString() })} />}
  </div>;
}

function FlightPlanEditor({ plan, mode, pending, error, onChange, onClose, onExport, onSubmit }: { plan: FlightPlan; mode: "new" | "edit"; pending: boolean; error: string; onChange: (plan: FlightPlan) => void; onClose: () => void; onExport: () => void; onSubmit: () => void }) {
  return <div className="modal-backdrop" role="presentation"><section className="modal-panel flight-editor-modal" role="dialog" aria-modal="true" aria-label={mode === "new" ? "新建飞行计划" : "编辑飞行计划"}>
    <header className="flight-editor-header"><div><span className="flight-editor-kicker"><FileText size={14} />{mode === "new" ? "NEW FLIGHT PLAN" : "SAVED FLIGHT PLAN"}</span><h2>{mode === "new" ? "新建飞行计划" : "编辑飞行计划"}</h2><p>整理航班基础信息、机场与计划航路。</p></div><button className="flight-editor-close" onClick={onClose} aria-label="关闭"><X size={20} /></button></header>
    <form className="flight-editor-form" onSubmit={(event) => { event.preventDefault(); onSubmit(); }}>
      <div className="flight-route-summary"><div><PlaneTakeoff size={18} /><span>出发</span><strong>{plan.departure || "----"}</strong></div><div className="flight-route-line"><i /><Plane size={24} /><i /></div><div><PlaneLanding size={18} /><span>到达</span><strong>{plan.arrival || "----"}</strong></div><small>{plan.alternate ? `备降机场 ${plan.alternate}` : "尚未设置备降机场"}</small></div>
      <section className="flight-editor-section"><div className="flight-editor-section-title"><Gauge size={17} /><div><strong>航班信息</strong><span>呼号、机型和巡航计划</span></div></div><div className="flight-editor-grid"><Field label="航班呼号" value={plan.callsign} onChange={(callsign) => onChange({ ...plan, callsign })} placeholder="例如 SJX346" /><Field label="机型" value={plan.aircraft} onChange={(aircraft) => onChange({ ...plan, aircraft })} placeholder="例如 A359" /><Field label="巡航高度" value={plan.cruiseAltitude} onChange={(cruiseAltitude) => onChange({ ...plan, cruiseAltitude })} placeholder="例如 FL410" /><label className="form-field"><span>预计起飞时间</span><div className="flight-input-icon"><CalendarClock size={16} /><input type="datetime-local" value={plan.etd} onChange={(event) => onChange({ ...plan, etd: event.target.value })} /></div></label></div></section>
      <section className="flight-editor-section"><div className="flight-editor-section-title"><PlaneTakeoff size={17} /><div><strong>机场</strong><span>使用四字 ICAO 代码</span></div></div><div className="flight-airport-grid"><Field label="出发机场" value={plan.departure} onChange={(departure) => onChange({ ...plan, departure: departure.toUpperCase() })} placeholder="RCTP" /><Field label="到达机场" value={plan.arrival} onChange={(arrival) => onChange({ ...plan, arrival: arrival.toUpperCase() })} placeholder="RJTT" /><Field label="备降机场" value={plan.alternate ?? ""} onChange={(alternate) => onChange({ ...plan, alternate: alternate.toUpperCase() })} placeholder="RJGG" /></div></section>
      <section className="flight-editor-section"><div className="flight-editor-section-title"><Route size={17} /><div><strong>计划航路</strong><span>支持航路、航路点和直飞指令</span></div></div><label className="form-field flight-route-field"><textarea value={plan.route} onChange={(event) => onChange({ ...plan, route: event.target.value })} placeholder="例如 MOLKA1A MOLKA M750 BILLY Y21 AKSEL…" /><small>{plan.route.trim() ? `${plan.route.trim().split(/\s+/).length} 个航路元素` : "尚未填写航路"}</small></label></section>
      {error && <p className="form-error flight-editor-error">保存失败：{error}</p>}
      <footer className="flight-editor-actions"><button type="button" className="button secondary" onClick={onExport}><Download size={17} />导出 JSON</button><span /><button type="button" className="button secondary" onClick={onClose}>取消</button><button className="button primary" disabled={pending}><Save size={17} />{pending ? "正在保存" : mode === "new" ? "创建计划" : "保存修改"}</button></footer>
    </form>
  </section></div>;
}

function Field({ label, value, onChange, placeholder }: { label: string; value: string; onChange: (value: string) => void; placeholder?: string }) { return <label className="form-field"><span>{label}</span><input value={value} onChange={(event) => onChange(event.target.value)} placeholder={placeholder} /></label>; }
